#Creative Strong Box
mods.extendedcrafting.TableCrafting.addShaped(<thermalexpansion:strongbox>.withTag({RSControl: 0 as byte, Creative: 1 as byte, Level: 4 as byte}), [
[<draconicevolution:chaotic_core>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <draconicevolution:chaotic_core>], 
[<avaritia:resource:6>, <botania:blackholetalisman>.withTag({}), <aether_legacy:enchanted_gravitite>, <aether_legacy:enchanted_gravitite>, <aether_legacy:enchanted_gravitite>, <aether_legacy:enchanted_gravitite>, <aether_legacy:enchanted_gravitite>, <botania:blackholetalisman>.withTag({}), <avaritia:resource:6>], 
[<avaritia:resource:6>, <aether_legacy:enchanted_gravitite>, <industrialforegoing:black_hole_unit>, <extendedcrafting:singularity:50>, <extendedcrafting:singularity:27>, <extendedcrafting:singularity:50>, <industrialforegoing:black_hole_unit>, <aether_legacy:enchanted_gravitite>, <avaritia:resource:6>], 
[<avaritia:resource:6>, <aether_legacy:enchanted_gravitite>, <extendedcrafting:singularity:48>, <botania:manaresource:21>, <avaritia:matter_cluster>, <botania:manaresource:21>, <extendedcrafting:singularity:48>, <aether_legacy:enchanted_gravitite>, <avaritia:resource:6>], 
[<avaritia:resource:6>, <aether_legacy:enchanted_gravitite>, <extendedcrafting:singularity:27>, <avaritia:matter_cluster>, <draconicevolution:draconium_chest>, <avaritia:matter_cluster>, <extendedcrafting:singularity:27>, <aether_legacy:enchanted_gravitite>, <avaritia:resource:6>], 
[<avaritia:resource:6>, <aether_legacy:enchanted_gravitite>, <extendedcrafting:singularity:48>, <botania:manaresource:21>, <avaritia:matter_cluster>, <botania:manaresource:21>, <extendedcrafting:singularity:48>, <aether_legacy:enchanted_gravitite>, <avaritia:resource:6>], 
[<avaritia:resource:6>, <aether_legacy:enchanted_gravitite>, <industrialforegoing:black_hole_unit>, <extendedcrafting:singularity:50>, <extendedcrafting:singularity:27>, <extendedcrafting:singularity:50>, <industrialforegoing:black_hole_unit>, <aether_legacy:enchanted_gravitite>, <avaritia:resource:6>], 
[<avaritia:resource:6>, <botania:blackholetalisman>.withTag({}), <aether_legacy:enchanted_gravitite>, <aether_legacy:enchanted_gravitite>, <aether_legacy:enchanted_gravitite>, <aether_legacy:enchanted_gravitite>, <aether_legacy:enchanted_gravitite>, <botania:blackholetalisman>.withTag({}), <avaritia:resource:6>], 
[<draconicevolution:chaotic_core>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <draconicevolution:chaotic_core>]]); 

#Creative Fluid Tank
mods.extendedcrafting.TableCrafting.addShaped(<mekanism:machineblock2:11>.withTag({Tier: 4}), [
[<forge:bucketfilled>.withTag({FluidName: "biofuel", Amount: 1000}), <industrialforegoing:black_hole_tank>, <forge:bucketfilled>.withTag({FluidName: "if.protein", Amount: 1000}), <industrialforegoing:black_hole_tank>, <minecraft:water_bucket>, <openblocks:tank>, <forge:bucketfilled>.withTag({FluidName: "lubricant", Amount: 1000}), <openblocks:tank>, <forge:bucketfilled>.withTag({FluidName: "naphtha", Amount: 1000})], 
[<industrialforegoing:black_hole_tank>, <mekanism:controlcircuit:3>, <extrabotany:elfjar>, <extrabotany:elfjar>, <nuclearcraft:water_source_dense>, <agricraft:water_tank>.withTag({agri_material_meta: 0, agri_material: "minecraft:planks"}), <agricraft:water_tank>.withTag({agri_material_meta: 0, agri_material: "minecraft:planks"}), <mekanism:controlcircuit:3>, <openblocks:tank>], 
[<forge:bucketfilled>.withTag({FluidName: "essence", Amount: 1000}), <extrabotany:elfjar>, <forge:bucketfilled>.withTag({FluidName: "creosote", Amount: 1000}), <mysticalagriculture:crafting:48>, <forge:bucketfilled>.withTag({FluidName: "petrotheum", Amount: 1000}), <mysticalagriculture:crafting:48>, <forge:bucketfilled>.withTag({FluidName: "ender", Amount: 1000}), <agricraft:water_tank>.withTag({agri_material_meta: 0, agri_material: "minecraft:planks"}), <forge:bucketfilled>.withTag({FluidName: "kerosene", Amount: 1000})], 
[<industrialforegoing:black_hole_tank>, <extrabotany:elfjar>, <mysticalagriculture:crafting:48>, <extendedcrafting:material:19>, <extendedcrafting:material:13>, <extendedcrafting:material:19>, <mysticalagriculture:crafting:48>, <agricraft:water_tank>.withTag({agri_material_meta: 0, agri_material: "minecraft:planks"}), <openblocks:tank>], 
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: 1000}), <nuclearcraft:water_source_dense>, <forge:bucketfilled>.withTag({FluidName: "glowstone", Amount: 1000}), <extendedcrafting:material:13>, <mekanism:machineblock2:11>.withTag({tier: 3}), <extendedcrafting:material:13>, <forge:bucketfilled>.withTag({FluidName: "aerotheum", Amount: 1000}), <nuclearcraft:water_source_dense>, <forge:bucketfilled>.withTag({FluidName: "helium3", Amount: 1000})], 
[<tconstruct:seared_tank>, <enderio:block_tank>, <mysticalagriculture:crafting:48>, <extendedcrafting:material:19>, <extendedcrafting:material:13>, <extendedcrafting:material:19>, <mysticalagriculture:crafting:48>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 4 as byte}), <magneticraft:small_tank>.withTag({})], 
[<forge:bucketfilled>.withTag({FluidName: "blueslime", Amount: 1000}), <enderio:block_tank>, <forge:bucketfilled>.withTag({FluidName: "heavywater", Amount: 1000}), <mysticalagriculture:crafting:48>, <forge:bucketfilled>.withTag({FluidName: "biodiesel", Amount: 1000}), <mysticalagriculture:crafting:48>, <forge:bucketfilled>.withTag({FluidName: "redstone", Amount: 1000}), <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 4 as byte}), <forge:bucketfilled>.withTag({FluidName: "pyrotheum", Amount: 1000})], 
[<tconstruct:seared_tank>, <mekanism:controlcircuit:3>, <enderio:block_tank>, <enderio:block_tank>, <nuclearcraft:water_source_dense>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 4 as byte}), <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 4 as byte}), <mekanism:controlcircuit:3>, <magneticraft:small_tank>.withTag({})], 
[<forge:bucketfilled>.withTag({FluidName: "neutron", Amount: 1000}), <tconstruct:seared_tank>, <forge:bucketfilled>.withTag({FluidName: "purpleslime", Amount: 1000}), <tconstruct:seared_tank>, <minecraft:lava_bucket>, <magneticraft:small_tank>.withTag({}), <forge:bucketfilled>.withTag({FluidName: "astralsorcery.liquidstarlight", Amount: 1000}), <magneticraft:small_tank>.withTag({}), <forge:bucketfilled>.withTag({FluidName: "cryotheum", Amount: 1000})]]); 

#Creative Gas Tank
mods.extendedcrafting.TableCrafting.addShaped(<mekanism:gastank>.withTag({tier: 4}), [
[<mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "hydrogen"}}}), <industrialforegoing:black_hole_tank>, <mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "tritium"}}}), <industrialforegoing:black_hole_tank>, <mekanism:machineblock3:1>, <openblocks:tank>, <mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "lithium"}}}), <openblocks:tank>, <mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "fusionfuel"}}})], 
[<industrialforegoing:black_hole_tank>, <mekanism:controlcircuit:3>, <extrabotany:elfjar>, <extrabotany:elfjar>, <nuclearcraft:water_source_dense>, <agricraft:water_tank>.withTag({agri_material_meta: 0, agri_material: "minecraft:planks"}), <agricraft:water_tank>.withTag({agri_material_meta: 0, agri_material: "minecraft:planks"}), <mekanism:controlcircuit:3>, <openblocks:tank>], 
[<mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "oxygen"}}}), <extrabotany:elfjar>, <ore:crystalIron>, <mysticalagriculture:crafting:48>, <mekanism:gasupgrade>, <mysticalagriculture:crafting:48>, <ore:crystalLead>, <agricraft:water_tank>.withTag({agri_material_meta: 0, agri_material: "minecraft:planks"}), <mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "deuterium"}}})], 
[<industrialforegoing:black_hole_tank>, <extrabotany:elfjar>, <mysticalagriculture:crafting:48>, <extendedcrafting:material:19>, <extendedcrafting:material:13>, <extendedcrafting:material:19>, <mysticalagriculture:crafting:48>, <agricraft:water_tank>.withTag({agri_material_meta: 0, agri_material: "minecraft:planks"}), <openblocks:tank>], 
[<mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "water"}}}), <nuclearcraft:water_source_dense>, <ore:crystalGold>, <extendedcrafting:material:13>, <mekanism:gastank>.withTag({tier: 3}), <extendedcrafting:material:13>, <ore:crystalSilver>, <nuclearcraft:water_source_dense>, <mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "sodium"}}})], 
[<tconstruct:seared_tank>, <enderio:block_tank>, <mysticalagriculture:crafting:48>, <extendedcrafting:material:19>, <extendedcrafting:material:13>, <extendedcrafting:material:19>, <mysticalagriculture:crafting:48>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 4 as byte}), <magneticraft:small_tank>.withTag({})], 
[<mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "chlorine"}}}), <enderio:block_tank>, <mekanism:crystal:2>, <mysticalagriculture:crafting:48>, <mekanism:crystal:3>, <mysticalagriculture:crafting:48>, <ore:crystalTin>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 4 as byte}), <mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "brine"}}})], 
[<tconstruct:seared_tank>, <mekanism:controlcircuit:3>, <enderio:block_tank>, <enderio:block_tank>, <nuclearcraft:water_source_dense>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 4 as byte}), <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 4 as byte}), <mekanism:controlcircuit:3>, <magneticraft:small_tank>.withTag({})], 
[<mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "sulfurdioxide"}}}), <tconstruct:seared_tank>, <mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "sulfurtrioxide"}}}), <tconstruct:seared_tank>, <mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "sulfuricacid"}}}), <magneticraft:small_tank>.withTag({}), <mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "hydrogenchloride"}}}), <magneticraft:small_tank>.withTag({}), <mekanism:gastank>.withTag({Tier: 0, mekData: {stored: {amount: 64000, gasName: "ethene"}}})]]);  

#Creative Energy Cell
mods.extendedcrafting.TableCrafting.addShaped(<mekanism:energycube>.withTag({tier: 4, mekData: {energyStored: 1.7976931348623157E308}}), [
[<ore:blockLumium>, <extendedcrafting:storage:3>, <extendedcrafting:storage:3>, <extendedcrafting:material:19>, <extendedcrafting:material:13>, <extendedcrafting:material:19>, <extendedcrafting:storage:3>, <extendedcrafting:storage:3>, <ore:blockLumium>], 
[<extendedcrafting:storage:3>, <ore:fuelHECf249>, <thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <ore:fuelHECf249>,<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}),<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <ore:fuelHECf249>, <extendedcrafting:storage:3>], 
[<extendedcrafting:storage:3>,<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>,<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <extendedcrafting:storage:3>], 
[<extendedcrafting:storage:3>,<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <draconicevolution:draconium_capacitor:1>, <environmentaltech:solar_cell_aethium>, <environmentaltech:solar_cell_aethium>, <environmentaltech:solar_cell_aethium>, <draconicevolution:draconium_capacitor:1>,<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <extendedcrafting:storage:3>], 
[<extendedcrafting:material:13>, <ore:fuelHECf249>, <draconicevolution:draconium_capacitor:1>, <environmentaltech:solar_cell_aethium>, <environmentaltech:solar_cell_aethium>, <environmentaltech:solar_cell_aethium>, <draconicevolution:draconium_capacitor:1>, <ore:fuelHECf249>, <extendedcrafting:material:13>], 
[<extendedcrafting:storage:3>,<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <draconicevolution:draconium_capacitor:1>, <environmentaltech:solar_cell_aethium>, <environmentaltech:solar_cell_aethium>, <environmentaltech:solar_cell_aethium>, <draconicevolution:draconium_capacitor:1>,<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <extendedcrafting:storage:3>], 
[<extendedcrafting:storage:3>,<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>,<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <extendedcrafting:storage:3>], 
[<extendedcrafting:storage:3>, <ore:fuelHECf249>,<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}),<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <ore:fuelHECf249>,<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}),<thermalexpansion:cell>.withTag({Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000}), <ore:fuelHECf249>, <extendedcrafting:storage:3>], 
[<ore:blockLumium>, <extendedcrafting:storage:3>, <extendedcrafting:storage:3>, <extendedcrafting:material:19>, <extendedcrafting:material:13>, <extendedcrafting:material:19>, <extendedcrafting:storage:3>, <extendedcrafting:storage:3>, <ore:blockLumium>]]);  

#The Ultimate Ingot
mods.extendedcrafting.TableCrafting.addShapeless(4, <extendedcrafting:material:32> * 1, [<minecraft:iron_ingot>, <minecraft:gold_ingot>, <mekanism:ingot:3>, <mekanism:ingot:0>, <projectred-core:resource_item:103>, <projectred-core:resource_item:104>, <tconstruct:ingots:3>, <tconstruct:ingots:4>, <tconstruct:ingots:5>,  <tconstruct:ingots:0>, <tconstruct:ingots:1>, <astralsorcery:itemcraftingcomponent:1>, <botania:manaresource:0>, <botania:manaresource:4>, <botania:manaresource:7>, <botania:manaresource:14>, <thermalfoundation:material:128>, <thermalfoundation:material:129>, <thermalfoundation:material:130>, <thermalfoundation:material:131>, <thermalfoundation:material:132>, <thermalfoundation:material:133>, <thermalfoundation:material:134>, <thermalfoundation:material:160>, <magneticraft:ingots:5>, <nuclearcraft:ingot:3>, <nuclearcraft:ingot:4>, <nuclearcraft:ingot:5>, <nuclearcraft:ingot:6>, <nuclearcraft:ingot:7>, <nuclearcraft:ingot:9>, <nuclearcraft:ingot:10>, <nuclearcraft:ingot:11>, <psi:material:1>, <enderio:item_alloy_ingot:0>, <enderio:item_alloy_ingot:1>, <enderio:item_alloy_ingot:2>, <enderio:item_alloy_ingot:3>, <enderio:item_alloy_ingot:4>, <enderio:item_alloy_ingot:5>, <enderio:item_alloy_ingot:6>, <enderio:item_alloy_ingot:7>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:9>, <enderio:item_material:72>, <extrabotany:material:5>, <extrabotany:material:8>, <draconicevolution:draconium_ingot>, <draconicevolution:draconic_ingot>, <refinedstorage:quartz_enriched_iron>, <simplyjetpacks:metaitemmods:3>, <plustic:alumiteingot>, <plustic:osgloglasingot>, <plustic:osmiridiumingot>, <tconstruct:ingots:2>, <tp:lapis_ingot>, <tp:redstone_ingot>, <thermalfoundation:material:161>, <thermalfoundation:material:162>, <thermalfoundation:material:163>, <thermalfoundation:material:164>, <thermalfoundation:material:165>, <thermalfoundation:material:166>, <thermalfoundation:material:167>, <nuclearcraft:alloy:1>, <nuclearcraft:alloy:2>, <nuclearcraft:alloy:3>, <nuclearcraft:alloy:4>, <nuclearcraft:alloy:6>, <nuclearcraft:alloy:10>, <nuclearcraft:alloy:11>, <nuclearcraft:alloy:12>, <nuclearcraft:alloy:13>, <nuclearcraft:alloy:15>]);

#The Ultimate Singularity
mods.extendedcrafting.TableCrafting.addShapeless(4, <extendedcrafting:singularity_ultimate> * 1, [<extendedcrafting:singularity:0>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity:2>, <extendedcrafting:singularity:4>, <extendedcrafting:singularity:5>, <extendedcrafting:singularity:6>, <extendedcrafting:singularity:7>, <extendedcrafting:singularity:16>, <extendedcrafting:singularity:17>,  <extendedcrafting:singularity:18>, <extendedcrafting:singularity:19>, <extendedcrafting:singularity:22>, <extendedcrafting:singularity:23>, <extendedcrafting:singularity:24>, <extendedcrafting:singularity:25>, <extendedcrafting:singularity:26>, <extendedcrafting:singularity:27>, <extendedcrafting:singularity:28>, <extendedcrafting:singularity:32>, <extendedcrafting:singularity:34>, <extendedcrafting:singularity:35>, <extendedcrafting:singularity:48>, <extendedcrafting:singularity:49>, <extendedcrafting:singularity:50>, <extendedcrafting:singularity:64>, <extendedcrafting:singularity:65>, <extendedcrafting:singularity:66>]);

#Creative Modifier
mods.extendedcrafting.TableCrafting.addShaped(<tconstruct:materials:50> * 1, [[<tconstruct:materials:19>, <tconstruct:cast:0>, <tconstruct:cast:0>, <tconstruct:cast:0>, <tconstruct:materials:13>, <tconstruct:cast:0>, <tconstruct:cast:0>, <tconstruct:cast:0>, <tconstruct:materials:19>], [<tconstruct:cast:0>, <tconstruct:materials:9>, <tconstruct:firewood:1>, <plustic:alumiteingot>, <tconstruct:book>, <plustic:osmiridiumingot>, <tconstruct:firewood:1>, <tconstruct:materials:9>, <tconstruct:cast:0>], [<tconstruct:cast:0>, <tconstruct:firewood:1>, <tconstruct:materials:10>, <draconicevolution:draconic_ingot>, <minecraft:nether_star>, <draconicevolution:draconic_ingot>, <tconstruct:materials:10>, <tconstruct:firewood:1>, <tconstruct:cast:0>], [<tconstruct:cast:0>, <plustic:alumiteingot>, <draconicevolution:draconic_ingot>, <tconstruct:materials:11>, <tconstruct:edible:33>, <tconstruct:materials:11>, <draconicevolution:draconic_ingot>, <plustic:osmiridiumingot>, <tconstruct:cast:0>], [<tconstruct:materials:12>, <tconstruct:book>, <minecraft:nether_star>, <tconstruct:edible:33>, <minecraft:skull:3>.withTag({}), <tconstruct:edible:33>, <minecraft:nether_star>, <tconstruct:book>, <tconstruct:materials:12>], [<tconstruct:cast:0>, <plustic:osgloglasingot>, <draconicevolution:draconic_ingot>, <tconstruct:materials:11>, <tconstruct:edible:33>, <tconstruct:materials:11>, <draconicevolution:draconic_ingot>, <plustic:mirioningot>, <tconstruct:cast:0>], [<tconstruct:cast:0>, <tconstruct:firewood:1>, <tconstruct:materials:10>, <draconicevolution:draconic_ingot>, <minecraft:nether_star>, <draconicevolution:draconic_ingot>, <tconstruct:materials:10>, <tconstruct:firewood:1>, <tconstruct:cast:0>], [<tconstruct:cast:0>, <tconstruct:materials:9>, <tconstruct:firewood:1>, <plustic:osgloglasingot>, <tconstruct:book>, <plustic:mirioningot>, <tconstruct:firewood:1>, <tconstruct:materials:9>, <tconstruct:cast:0>], [<tconstruct:materials:19>, <tconstruct:cast:0>, <tconstruct:cast:0>, <tconstruct:cast:0>, <tconstruct:materials:13>, <tconstruct:cast:0>, <tconstruct:cast:0>, <tconstruct:cast:0>, <tconstruct:materials:19>]]);

#The Everlasting Guilty Pool
mods.extendedcrafting.TableCrafting.addShaped(<botania:pool:1> * 1, [
[<extrabotany:quantummanabuffer>, <botania:specialflower>.withTag({type: "moonbless"}), <botania:specialflower>.withTag({type: "omniviolet"}), <astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.discidia"}}), <botania:specialflower>.withTag({type: "entropinnyum"}), <astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.armara"}}), <botania:specialflower>.withTag({type: "thermalily"}), <botania:specialflower>.withTag({type: "spectrolus"}), <extrabotany:quantummanabuffer>], 
[<botania:specialflower>.withTag({type: "hydroangeas"}), <extendedcrafting:material:19>, <botania:manaresource:7>, <botania:manaresource:7>, <extendedcrafting:material:13>, <botania:manaresource:7>, <botania:manaresource:7>, <extendedcrafting:material:19>, <botania:specialflower>.withTag({type: "arcanerose"})], 
[<botania:specialflower>.withTag({type: "rafflowsia"}), <botania:manaresource:7>, <botania:specialflower>.withTag({type: "rafflowsia"}), <botania:manaresource:14>, <extrabotany:cosmetic:8>, <botania:manaresource:14>, <botania:specialflower>.withTag({type: "edelweiss"}), <botania:manaresource:7>, <botania:specialflower>.withTag({type: "munchdew"})], 
[<astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.vicio"}}), <botania:manaresource:7>, <botania:manaresource:14>, <botania:manatablet>.withTag({mana: 500000}), <astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.aevitas"}}), <botania:manatablet>.withTag({mana: 500000}), <botania:manaresource:14>, <botania:manaresource:7>, <astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.evorsio"}})], 
[<extrabotany:blockorichalcos>, <extendedcrafting:material:13>, <botania:specialflower>.withTag({type: "dandelifeon"}), <astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.lucerna"}}), <botania:pool:0>, <astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.mineralis"}}), <botania:specialflower>.withTag({type: "kekimurus"}), <extendedcrafting:material:13>, <extrabotany:blockorichalcos>], 
[<astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.horologium"}}), <botania:manaresource:7>, <botania:manaresource:14>, <botania:manatablet>.withTag({mana: 500000}), <astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.octans"}}), <botania:manatablet>.withTag({mana: 500000}), <botania:manaresource:14>, <botania:manaresource:7>, <astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.bootes"}})], 
[<botania:specialflower>.withTag({type: "bloodyenchantress"}), <botania:manaresource:7>, <botania:specialflower>.withTag({type: "endoflame"}), <botania:manaresource:14>, <botania:lexicon>.withTag({"knowledge.minecraft": 1 as byte, "knowledge.alfheim": 1 as byte, "knowledge.dream": 1 as byte, "knowledge.relic": 1 as byte}), <botania:manaresource:14>,<botania:specialflower>.withTag({type: "shulk_me_not"}), <botania:manaresource:7>, <botania:specialflower>.withTag({type: "gourmaryllis"})], 
[<botania:specialflower>.withTag({type: "sunbless"}), <extendedcrafting:material:19>, <botania:manaresource:7>, <botania:manaresource:7>, <extendedcrafting:material:13>, <botania:manaresource:7>, <botania:manaresource:7>, <extendedcrafting:material:19>, <botania:specialflower>.withTag({type: "narslimmus"})], 
[<extrabotany:quantummanabuffer>, <botania:specialflower>.withTag({type: "tinkle"}), <botania:specialflower>.withTag({type: "bellflower"}), <astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.fornax"}}), <extrabotany:blockorichalcos>, <astralsorcery:itemtunedcelestialcrystal>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.pelotrio"}}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "geminiorchid"}), <extrabotany:quantummanabuffer>]]);

#Creative Jetpack
mods.extendedcrafting.TableCrafting.addShaped(<simplyjetpacks:itemjetpack:0> * 1, [[null, <extendedcrafting:material:19>, null, null, null, null, null, <extendedcrafting:material:19>, null], [null, <draconicevolution:draconium_block:1>, null, null, null, null, null, <draconicevolution:draconium_block:1>, null], [<draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, null, null, null, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>], [<draconicevolution:draconium_block:1>, <actuallyadditions:block_crystal_empowered:0>, <draconicevolution:draconium_block:1>, <extendedcrafting:material:13>, <simplyjetpacks:itemjetpack:9>, <extendedcrafting:material:13>, <draconicevolution:draconium_block:1>, <actuallyadditions:block_crystal_empowered:0>, <draconicevolution:draconium_block:1>], [<draconicevolution:draconium_block:1>, <actuallyadditions:block_crystal_empowered:0>, <draconicevolution:draconium_block:1>, <mekanism:energycube>.withTag({tier: 3}), <mekanism:jetpack>, <mekanism:energycube>.withTag({tier: 3}), <draconicevolution:draconium_block:1>, <actuallyadditions:block_crystal_empowered:0>, <draconicevolution:draconium_block:1>], [<draconicevolution:draconium_block:1>, <actuallyadditions:block_crystal_empowered:0>, <draconicevolution:draconium_block:1>, <extendedcrafting:material:13>, <simplyjetpacks:itemjetpack:18>, <extendedcrafting:material:13>, <draconicevolution:draconium_block:1>, <actuallyadditions:block_crystal_empowered:0>, <draconicevolution:draconium_block:1>], [<draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, null, null, null, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>], [null, <extendedcrafting:material:19>, null, null, null, null, null, <extendedcrafting:material:19>, null], [<draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, null, null, null, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>, <draconicevolution:draconium_block:1>]]);

#Infinite Energy
mods.extendedcrafting.TableCrafting.addShaped(<magneticraft:infinite_energy:0> * 1, [[<magneticraft:multiblock_parts:0>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:0>], [<magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:3>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:2>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:3>, <magneticraft:multiblock_parts:5>], [<magneticraft:multiblock_parts:5>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:1>, <magneticraft:multiblock_parts:2>, <extendedcrafting:material:19>, <magneticraft:multiblock_parts:2>, <magneticraft:multiblock_parts:1>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:5>], [<magneticraft:multiblock_parts:5>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:2>, <extendedcrafting:material:13>, <magneticraft:multiblock_parts:4>, <extendedcrafting:material:13>, <magneticraft:multiblock_parts:2>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:5>], [<magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:2>, <extendedcrafting:material:19>, <magneticraft:multiblock_parts:4>, <magneticraft:thermopile:0>, <magneticraft:multiblock_parts:4>, <extendedcrafting:material:19>, <magneticraft:multiblock_parts:2>, <magneticraft:multiblock_parts:5>], [<magneticraft:multiblock_parts:5>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:2>, <extendedcrafting:material:13>, <magneticraft:multiblock_parts:4>, <extendedcrafting:material:13>, <magneticraft:multiblock_parts:2>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:5>], [<magneticraft:multiblock_parts:5>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:1>, <magneticraft:multiblock_parts:2>, <extendedcrafting:material:19>, <magneticraft:multiblock_parts:2>, <magneticraft:multiblock_parts:1>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:5>], [<magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:3>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:2>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_column:0>, <magneticraft:multiblock_parts:3>, <magneticraft:multiblock_parts:5>], [<magneticraft:multiblock_parts:0>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:5>, <magneticraft:multiblock_parts:0>]]);

#Creative CAD Assembly
mods.extendedcrafting.TableCrafting.addShaped(<psi:cad_assembly:5> * 1, [[null, null, <magneticraft:heavy_plates:2>, null, null, null, null, null, null], [null, <magneticraft:heavy_plates:2>, <magneticraft:heavy_plates:2>, <magneticraft:heavy_plates:2>, null, null, null, null, null], [<magneticraft:heavy_plates:2>, <magneticraft:heavy_plates:2>, <magneticraft:heavy_plates:2>, <extendedcrafting:material:19>, <magneticraft:heavy_plates:2>, null, null, null, null], [null, <magneticraft:heavy_plates:2>, <extendedcrafting:material:19>, <extendedcrafting:material:13>, <psi:cad_assembly:3>, <extendedcrafting:material:13>, null, null, null], [null, null, <magneticraft:heavy_plates:2>, <psi:cad_assembly:1>, <psi:cad_assembly:2>, <psi:cad_assembly:0>, <magneticraft:heavy_plates:2>, null, null], [null, null, null, <extendedcrafting:material:13>, <psi:cad_assembly:4>, <extendedcrafting:material:13>, <extendedcrafting:material:19>, <nuclearcraft:part:3>, null], [null, null, null, null, <nuclearcraft:part:3>, <extendedcrafting:material:19>, <nuclearcraft:part:3>, <nuclearcraft:part:3>, null], [null, null, null, <nuclearcraft:part:3>, <nuclearcraft:part:3>, <nuclearcraft:part:3>, <nuclearcraft:part:3>, null, null], [null, null, <nuclearcraft:part:3>, <nuclearcraft:part:3>, <nuclearcraft:part:3>, <nuclearcraft:part:3>, null, null, null]]);

// Endest Pearl
mods.extendedcrafting.TableCrafting.addShaped(<avaritia:endest_pearl> * 1, [[null, null, null, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, null, null, null], [null, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, null], [null, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, null], [<minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <avaritia:block_resource:0>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>], [<minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <avaritia:block_resource:0>, <extendedcrafting:storage:2>, <avaritia:block_resource:0>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>], [<enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <avaritia:block_resource:0>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>], [null, <enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>, null], [null, <enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, null], [null, null, null, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>, null, null, null]]);

// Infinity Catalyst
mods.extendedcrafting.TableCrafting.addShapeless(4, <avaritia:resource:5> * 1, [<enderio:item_alloy_endergy_ingot:1>, <avaritia:block_resource>, <avaritia:block_resource>, <avaritia:block_resource>, <avaritia:block_resource>, <avaritia:ultimate_stew>, <avaritia:ultimate_stew>, <avaritia:ultimate_stew>, <avaritia:ultimate_stew>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:endest_pearl>, <avaritia:endest_pearl>, <avaritia:endest_pearl>, <avaritia:endest_pearl>, <avaritia:resource:7>, <extendedcrafting:singularity_ultimate>, <draconicevolution:awakened_core>, <environmentaltech:aethium_crystal>, <environmentaltech:mica>, <extendedcrafting:material:0>, <extendedcrafting:material:24>, <extendedcrafting:material:36>, <mekanism:tierinstaller:3>, <industrialforegoing:pink_slime_ingot>, <mysticalagradditions:insanium:0>, <projectred-core:resource_item:103>, <projectred-core:resource_item:104>, <simplyjetpacks:metaitemmods:19>, <simplyjetpacks:metaitemmods:21>, <astralsorcery:itemcraftingcomponent:1>, <astralsorcery:itemcraftingcomponent:4>, <botania:manaresource:14>, <extrabotany:material:1>, <thermalfoundation:storage_alloy:7>, <nuclearcraft:depleted_fuel_californium:7>, <enderio:item_alloy_ingot:2>, <tconstruct:metal:2>, <furnaceoverhaul:zenith_furnace>, <aether_legacy:ambrosium_shard>, <aether_legacy:zanite_gemstone>, <aether_legacy:enchanted_gravitite>, <magneticraft:heavy_plates>, <psi:material>, <psi:material:1>, <psi:material:2>, <ironchest:iron_chest:5>, <ironchest:iron_chest:6>, <actuallyadditions:block_crystal_empowered>, <minecraft:shulker_shell>]);